In [1]:
import numpy as np 
import pandas as pd


In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=["cgpa","profile_score","lpa"])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [4]:
def initialize_parameter(layer_dims):
    parameters={}
    L=len(layer_dims)
    for l in range(1,L):
        parameters["w"+str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters["b"+str(l)]=np.zeros((layer_dims[l],1))

    return parameters

In [5]:
def linear_forward(A_prev, w, b):
    z=np.dot(w.T,A_prev)+b
    return z

In [19]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['w' + str(l)]
    bl = parameters['b' + str(l)]
    # print("A"+str(l-1)+": ", A_prev)
    # print("W"+str(l)+": ", Wl)
    # print("b"+str(l)+": ", bl)
    # print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    # print("A"+str(l)+": ", A)
    # print("**"*20)
          
  return A,A_prev

In [7]:
x=df[["cgpa","profile_score"]].values[0].reshape(2,1)
y=df[["lpa"]].values[0][0]

In [8]:
x,y

(array([[8],
        [8]]),
 np.int64(4))

In [9]:
parameters=initialize_parameter([2,2,1])
parameters

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [10]:
y_hat,a1=L_layer_forward(x,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [11]:
y_hat=y_hat[0][0]
y_hat

np.float64(0.32000000000000006)

In [12]:
(y-0.32)**2

np.float64(13.5424)

In [13]:
def update_paremeter(parameters,y,y_hat,a1,x):
    parameters["w2"][0][0]=parameters["w2"][0][0] +(0.001*2*(y-y_hat)*a1[0][0])
    parameters["w2"][1][0]=parameters["w2"][1][0] +(0.001*2*(y-y_hat)*a1[1][0])
    parameters["b2"][0][0]=parameters["b2"][0][0] +(0.001*2*(y-y_hat))

    parameters["w1"][0][0]=parameters["w1"][0][0] +(0.001*2*(y-y_hat)*parameters["w2"][0][0]*x[0][0])
    parameters["w1"][0][1]=parameters["w1"][0][1] +(0.001*2*(y-y_hat)*parameters["w2"][0][0]*x[1][0])
    parameters["b1"][0][0]=parameters["b1"][0][0] +(0.001*2*(y-y_hat)*parameters["w2"][0][0])

    parameters["w1"][1][0]=parameters["w1"][1][0] +(0.001*2*(y-y_hat)*parameters["w2"][1][0]*x[0][0])
    parameters["w1"][1][1]=parameters["w1"][1][1] +(0.001*2*(y-y_hat)*parameters["w2"][1][0]*x[1][0])
    parameters["b1"][1][0]=parameters["b1"][1][0] +(0.001*2*(y-y_hat)*parameters["w2"][1][0])   
    


In [14]:
update_paremeter(parameters,y,y_hat,a1,x)

In [15]:
parameters

{'w1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'w2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [16]:
x=df[["cgpa","profile_score"]].values[3].reshape(2,1)
y=df[["lpa"]].values[3][0]
y_hat,a1=L_layer_forward(x,parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.81270598]
 [1.81270598]]
****************************************
A1:  [[1.81270598]
 [1.81270598]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.00736]]
----------------------------------------
A2:  [[0.41259405]]
****************************************


In [21]:
parameters=initialize_parameter([2,2,1])
epochs = 5

for i in range(epochs):
    loss=[]
    for j in range(df.shape[0]):
        x=df[["cgpa","profile_score"]].values[j].reshape(2,1)
        y=df[["lpa"]].values[j][0]

        y_hat,a1=L_layer_forward(x,parameters)
        
        y_hat=y_hat[0][0]
        update_paremeter(parameters,y,y_hat,a1,x)
        loss.append((y-y_hat)**2)
    print(f"epoch-{i} | loss: {np.array(loss).mean()}")
parameters


epoch-0 | loss: 26.28249792398698
epoch-1 | loss: 19.438253848220803
epoch-2 | loss: 10.139874435827522
epoch-3 | loss: 3.385561305106485
epoch-4 | loss: 1.3198454128484565


{'w1': array([[0.273603  , 0.3993222 ],
        [0.28787155, 0.42586102]]),
 'b1': array([[0.02885522],
        [0.03133223]]),
 'w2': array([[0.42574893],
        [0.50219328]]),
 'b2': array([[0.11841278]])}

In [22]:
import torch 
import torch.nn as nn
import torch.optim as optim

In [31]:
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 2)
        self.fc2 = nn.Linear(2, 1)

        self._init_weights()

    def _init_weights(self):
        nn.init.constant_(self.fc1.weight, 0.1)
        nn.init.constant_(self.fc1.bias, 0.0)

        nn.init.constant_(self.fc2.weight, 0.1)
        nn.init.constant_(self.fc2.bias, 0.0)

    def forward(self, x):
        x = self.fc1(x)
        return self.fc2(x)



In [24]:
x=torch.tensor(df[["cgpa", "profile_score"]].values, dtype=torch.float32)
y = torch.tensor(df[["lpa"]].values, dtype=torch.float32)

In [39]:
model = SimpleNN()

criterion = nn.MSELoss()                # (y - y_hat)^2
optimizer = optim.SGD(model.parameters(), lr=0.001)


In [40]:
epoch = 100
prev_loss = float('inf')  # start with a very large value
for i in range(epoch):
    optimizer.zero_grad()
    y_hat = model(x)
    loss = criterion(y_hat, y)
    loss.backward()
    optimizer.step() 

    print(f"epoch-{i} | loss: {loss.item()}")

    # Early stopping
    if loss.item() > prev_loss:
        print("Loss increased — stopping early")
        break

    prev_loss = loss.item()


epoch-0 | loss: 28.01569938659668
epoch-1 | loss: 26.993473052978516
epoch-2 | loss: 25.79242706298828
epoch-3 | loss: 24.39017677307129
epoch-4 | loss: 22.77147674560547
epoch-5 | loss: 20.933269500732422
epoch-6 | loss: 18.890409469604492
epoch-7 | loss: 16.680767059326172
epoch-8 | loss: 14.367782592773438
epoch-9 | loss: 12.038021087646484
epoch-10 | loss: 9.79226016998291
epoch-11 | loss: 7.730470657348633
epoch-12 | loss: 5.934279918670654
epoch-13 | loss: 4.452544689178467
epoch-14 | loss: 3.295365333557129
epoch-15 | loss: 2.438281536102295
epoch-16 | loss: 1.8339885473251343
epoch-17 | loss: 1.4262551069259644
epoch-18 | loss: 1.1612534523010254
epoch-19 | loss: 0.9941037893295288
epoch-20 | loss: 0.8909258842468262
epoch-21 | loss: 0.827992856502533
epoch-22 | loss: 0.7896147966384888
epoch-23 | loss: 0.7658657431602478
epoch-24 | loss: 0.7506731748580933
epoch-25 | loss: 0.7404191493988037
epoch-26 | loss: 0.732986569404602
epoch-27 | loss: 0.727157711982727
epoch-28 | loss:

In [30]:
print(model.fc1.weight)
print(model.fc1.bias)
print(model.fc2.weight)
print(model.fc2.bias)


Parameter containing:
tensor([[-0.4775,  0.1635],
        [-0.7145, -0.5874]], requires_grad=True)
Parameter containing:
tensor([ 0.1876, -0.6251], requires_grad=True)
Parameter containing:
tensor([[-0.2930, -0.5249]], requires_grad=True)
Parameter containing:
tensor([-0.6836], requires_grad=True)
